Repository Team-Tempo/project-catwalk, pull requests merged in 2021-04, with the labels that each got.

#1 Initial app setup
  .gitignore
  client/components/App.jsx
  client/index.jsx
  dist/index.html
  dist/stylesheet.css
  dist/stylesheet.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: Ready for review

#21 Feature/Grid layout for Ratings module
  client/components/RatingsAndReviews/Rating/Factors.jsx
  client/components/RatingsAndReviews/Rating/RatingBreakdown.jsx
  client/components/RatingsAndReviews/Rating/RatingSummaryStars.jsx
  client/components/RatingsAndReviews/RatingsAndReviews.jsx
  client/components/RatingsAndReviews/Reviews/ReviewsList.jsx
  package-lock.json
  sampleData.json
Labels: Ready for review

#27 Feature/Related Products get requests
  client/components/App.jsx
  client/components/RelatedProducts/Related/RelatedProductCard.jsx
  client/components/RelatedProducts/Related/RelatedProductsList.jsx
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review

#31 Feature/implement dynamic rendering
  client/components/App.jsx
  client/components/RatingsAndReviews/Rating/Rating.jsx
  client/components/RatingsAndReviews/Rating/RatingBreakdown.jsx
  client/components/RatingsAndReviews/Rating/RatingSummaryStars.jsx
  client/components/RatingsAndReviews/RatingsAndReviews.jsx
  client/components/RatingsAndReviews/Reviews/Review.jsx
  client/components/RatingsAndReviews/Reviews/ReviewsList.jsx
Labels: Ready for review

#32 Feature/overview ratings
  client/components/ProductOverview/ProductInformation.jsx
  client/components/ProductOverview/ProductOverview.jsx
Labels: Ready for review

#30 Feature/outfit carousel and cards (review first)
  client/components/RelatedProducts/Outfit/BlankOutfitCard.jsx
  client/components/RelatedProducts/Outfit/CustomOutfitList.jsx
  client/components/RelatedProducts/Outfit/OutfitProductCard.jsx
  client/components/RelatedProducts/Related/RelatedProductCard.jsx
Labels: Ready for review

#34 Feature/add to outfit (review 2nd)
  client/components/App.jsx
  client/components/RelatedProducts/Outfit/BlankOutfitCard.jsx
  client/components/RelatedProducts/Outfit/CustomOutfitList.jsx
  client/components/RelatedProducts/Outfit/OutfitProductCard.jsx
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review

#35 Remove card from outfit list when X icon is clicked
  client/components/RelatedProducts/Outfit/CustomOutfitList.jsx
  client/components/RelatedProducts/Outfit/OutfitProductCard.jsx
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review

#37 Feature/overview add to cart
  client/components/ProductOverview/AddToCart.jsx
  client/components/ProductOverview/ProductOverview.jsx
Labels: Ready for review

#41 Just some clean-up! Removing unused style class and other old code
  client/components/ProductOverview/ImageGallery.jsx
Labels: Reviewed by Amanda

#40 Add More Questions Button
  client/components/QuestionsAndAnswers/QAndAComponents/Helpful.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/QuestionSearch.jsx
  client/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx
Labels: Reviewed by Julia

#44 Feature/helpfulness click
  client/components/QuestionsAndAnswers/QAndAComponents/Answer.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/Helpful.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/QAndA.jsx
  client/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx
Labels: Reviewed by Amanda

#42 Feature/related reviews: merge 1st!
  client/components/RelatedProducts/Related/RelatedProductCard.jsx
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review, Reviewed by Julia

#43 Feature/comparison modal
  client/components/RelatedProducts/ComparisonModal.jsx
  client/components/RelatedProducts/Related/RelatedProductCard.jsx
  client/components/RelatedProducts/Related/RelatedProductsList.jsx
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review, Reviewed by Julia

#48 Feature/add new review
  client/components/RatingsAndReviews/RatingsAndReviews.jsx
  client/components/RatingsAndReviews/Reviews/AddReview.jsx
  client/components/RatingsAndReviews/Reviews/AddReviewDialog.jsx
  client/components/RatingsAndReviews/Reviews/AddReviewForm.jsx
  client/components/RatingsAndReviews/Reviews/ReviewsList.jsx
Labels: Ready for review, Reviewed by Amanda

#47 Feature: Click RelatedProductCard and it will change the current product to that one
  client/components/App.jsx
  client/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx
  client/components/RelatedProducts/Related/RelatedProductCard.jsx
  client/components/RelatedProducts/Related/RelatedProductsList.jsx
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review, Reviewed by Julia

#52 Added zoom button which renders image a large as possible with backdrop
  client/components/ProductOverview/ImageGallery.jsx
Labels: Reviewed by Amanda

#51 Fixed bug related to comparison modal and changing the current product
  client/components/RelatedProducts/Related/RelatedProductCard.jsx
Labels: Ready for review, Reviewed by Julia

#54 Disables selecting out of stock sizes
  client/components/ProductOverview/AddToCart.jsx
Labels: Reviewed by Amanda

#56 Feature/outfit local storage
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review, Reviewed by Julia

#53 Task/ratings to use live data
  client/components/App.jsx
  client/components/RatingsAndReviews/Rating/Rating.jsx
  client/components/RatingsAndReviews/Rating/RatingBreakdown.jsx
  client/components/RatingsAndReviews/Rating/RatingSummaryStars.jsx
  client/components/RatingsAndReviews/RatingsAndReviews.jsx
Labels: Ready for review, Reviewed by Dylan

#57 Removed zoom button and changed cursors throughout overview
  client/components/ProductOverview/AddToCart.jsx
  client/components/ProductOverview/ImageGallery.jsx
  client/components/ProductOverview/ProductOverview.jsx
  client/components/ProductOverview/StyleSelector.jsx
  sampleData.json
Labels: Reviewed by Amanda

#59 Added some placeholder links to the header
  client/components/Header.jsx
Labels: Reviewed by Dylan

#61 Feature/implement scroll
  client/components/RatingsAndReviews/Rating/RatingSummaryStars.jsx
  client/components/RatingsAndReviews/RatingsAndReviews.jsx
  client/components/RatingsAndReviews/Reviews/ReviewsList.jsx
Labels: Reviewed by Amanda

#58 Styled carousel arrows and removed pagination dot
  client/components/RelatedProducts/Related/RelatedProductsList.jsx
  client/stylesheets/index.scss
Labels: Ready for review

#62 Changed text in headers into buttons
  client/components/Header.jsx
Labels: Ready for review, good first issue

#60 Feature/add question
  client/components/App.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/AddQuestion.jsx
  client/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx
Labels: Ready for review

#67 Optimization: Changed url to thumbnail_url for related and outfit lists
  client/components/RelatedProducts/Related/RelatedProductCard.jsx
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review, Reviewed by Julia

#68 See More Answers Feature and Styling
  client/components/QuestionsAndAnswers/QAndAComponents/AddAnswer.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/AddQuestion.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/Answer.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/Helpful.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/QAndA.jsx
  client/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx
Labels: Ready for review, Reviewed by Amanda

#65 Changed native alert to Snackbar when user tries to add duplicate outfit to CustomOutfitList
  client/components/RelatedProducts/RelatedProducts.jsx
Labels: Ready for review, Reviewed by Dylan

#64 Feature/style comparison modal
  client/components/RelatedProducts/ComparisonModal.jsx
  client/components/RelatedProducts/Related/RelatedProductCard.jsx
Labels: Ready for review, Reviewed by Julia

#66 Feature/implement rating
  client/components/App.jsx
  client/components/RatingsAndReviews/Rating/Factors.jsx
  client/components/RatingsAndReviews/Rating/Rating.jsx
  client/components/RatingsAndReviews/Rating/RatingBreakdown.jsx
Labels: Ready for review, Reviewed by Amanda

#70 Added scrollbar to Q and A
  client/components/QuestionsAndAnswers/QAndAComponents/AddQuestion.jsx
  client/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx
Labels: Ready for review, Reviewed by Julia

#74 Readme
  README.md
Labels: Ready for review, Reviewed by Dylan

#77 Q&A: Bug Fixes and Styling
  client/components/QuestionsAndAnswers/QAndAComponents/AddAnswer.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/AddQuestion.jsx
  client/components/QuestionsAndAnswers/QAndAComponents/Answer.jsx
  client/components/QuestionsAndAnswers/QuestionsAndAnswers.jsx
Labels: Ready for review, Reviewed by Julia

#80 README Q and A Update
  README.md
Labels: Ready for review, Reviewed by Amanda

#81 Added a readme and added a new section
  README.md
Labels: Reviewed by Amanda
